### ISSUE TITLE
Check if gulp-cli is already installed in ./configure

### ISSUE THREAD

**Issue by notpushkin** [reo7sp/reo-web-starter-kit#1]
So no sudo password is asked.

(By the way, if you need that complex configuration to start a project from the kit, I believe a [Yeoman](https://www.npmjs.com/package/yo) generator would suit your needs better here :-)

**Comment by notpushkin** [comment]
As an alternative, you could just remind the user to install gulp-cli if they haven't yet, and don't touch anything global by yourself.

**Comment by reo7sp** [comment]
Thanks for response!

Fixed by d55dafdb79e73f19b6b0732d02e62a4fd53a823e and b231cb10f4310ce877e2cbeeb977bf1c9c2d20d8
